trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: DeleteFiles@1
      displayName: 'Delete $(System.DefaultWorkingDirectory)\azure-pipelines.yml'
      inputs:
        SourceFolder: '$(System.DefautlWorkingDirectory)'
        Contents: 'azure-pipelines.yml'
    - task: DeleteFiles@1
      displayName: 'Delete $(System.DefaultWorkingDirectory)\.git'
      inputs:
        SourceFolder: '$(System.DefautlWorkingDirectory)'
        Contents: '.git'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(build.sourcesDirectory)'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
